import { defineCollection, defineContentConfig, z } from '@nuxt/content'

export default defineContentConfig({
  collections: {
    blog: defineCollection({
      source: 'blog/**',
      type: 'page',
      schema: z.object({
        date: z.string(),
        category: z.string(),
        readTime: z.string(),
        image: z.string(),
      }),
    }),
    projects: defineCollection({
      source: 'projects/**',
      type: 'page',
      schema: z.object({
        title: z.string(),
        description: z.string(),
        published: z.boolean().default(false),
        featured: z.boolean().default(false),
        cover: z.string().optional(),
        client: z.string().optional(),
        industry: z.string().optional(),
        services: z.array(z.string()).default([]),
        technologies: z.array(z.string()).default([]),
        completionDate: z.string().optional(),
        duration: z.string().optional(),
        projectUrl: z.string().optional(),
        githubUrl: z.string().optional(),
        challenge: z.string().optional(),
        solution: z.string().optional(),
        outcome: z.string().optional(),
        seoTitle: z.string().optional(),
        seoDescription: z.string().optional(),
      }),
    }),
    caseStudies: defineCollection({
      source: 'case-studies/**',
      type: 'page',
      schema: z.object({
        title: z.string(),
        description: z.string(),
        published: z.boolean().default(false),
        cover: z.string().optional(),
        client: z.string().optional(),
        industry: z.string().optional(),
        services: z.array(z.string()).default([]),
        technologies: z.array(z.string()).default([]),
        completionDate: z.string().optional(),
        projectSlug: z.string().optional(),
        introduction: z.string().optional(),
        businessProblem: z.string().optional(),
        objectives: z.array(z.string()).default([]),
        approach: z.string().optional(),
        results: z.array(z.string()).default([]),
        lessons: z.string().optional(),
        conclusion: z.string().optional(),
        seoTitle: z.string().optional(),
        seoDescription: z.string().optional(),
      }),
    }),
  },
})
